// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the user wants Nightingale to source songs from. Persisted in
 * `config.json` and consumed by both the scanner and the analyzer.
 */
export type LibrarySource =
  | { kind: "folder"; path: string }
  | {
      kind: "jellyfin";
      base_url: string;
      user_id: string;
      username: string;
      /**
       * Access token returned by `/Users/AuthenticateByName`. At rest in
       * `config.json` this value is an encrypted envelope; in-memory and
       * over IPC it's the plaintext token. See `secret.rs` for the on-disk
       * format + migration semantics.
       */
      access_token: string;
      /**
       * Stable per-install identifier we hand to Jellyfin in the
       * `X-Emby-Authorization` header. Generated once at connect time.
       */
      device_id: string;
    };
