// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shader-ready reactive frame. All values are slow-smoothed and ready to
 * pipe straight into shader uniforms — no second-stage processing on the
 * frontend. `hue` is a 0..1 phase, `flow` is a radians 0..2π angle, and
 * `wave` is the downsampled time-domain waveform for the oscilloscope shader.
 */
export type MicReactiveEvent = {
  volume: number;
  low: number;
  mid: number;
  high: number;
  centroid: number;
  pitch: number;
  energy: number;
  hue: number;
  flow: number;
  wave: Array<number>;
};
