// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the bytes for a song actually live. `LocalFile` means `Song.path` is the
 * real source-of-truth on disk; `Jellyfin` means `Song.path` is whatever the
 * adapter materialised locally (placeholder until first download).
 */
export type SongOrigin =
  | { kind: "local_file" }
  | { kind: "jellyfin"; item_id: string; base_url: string; container: string | null };
